apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-c
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/nguyenhieu8790/k8syaml.git
    targetRevision: HEAD
    path: appc
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - Replace=true
      - ServerSideApply=true
      - Validate=true    