---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-b
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: app-echo-b
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-echo-b
    spec:
      initContainers:
        - name: init-sleep
          image: busybox
          command: ["sleep", "180"]
          imagePullPolicy: Always
      containers:
        - image: jmalloc/echo-server
          imagePullPolicy: Always
          name: echo-b
          ports:
            - containerPort: 8080
