---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-a
  annotations:
    argocd.argoproj.io/sync-wave: "5"  
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: app-echo-a
  replicas: 3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-echo-a
    spec:
      initContainers:
        - name: init-sleep
          image: busybox
          command: ["sleep", "180"]
          imagePullPolicy: Always
      containers:
        - image: jmalloc/echo-server
          imagePullPolicy: Always
          name: echo-a
          ports:
            - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-b
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: app-echo-b
  replicas: 3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-echo-b
    spec:
      initContainers:
        - name: init-sleep
          image: busybox
          command: ["sleep", "180"]
          imagePullPolicy: Always
      containers:
        - image: jmalloc/echo-server
          imagePullPolicy: Always
          name: echo-b
          ports:
            - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-c
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: app-echo-c
  replicas: 3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-echo-c
    spec:
      initContainers:
        - name: init-sleep
          image: busybox
          command: ["sleep", "180"]
          imagePullPolicy: Always
      containers:
        - image: jmalloc/echo-server
          imagePullPolicy: Always
          name: echo-c
          ports:
            - containerPort: 8080             
